baseurl = "http://glciampaglia.com/"
title = "Giovanni Luca Ciampaglia"
copyright = "&copy; 2016 Giovanni Luca Ciampaglia"
languageCode = "en-us"
theme = "academic"

# Enable comments by entering your Disqus shortname
# disqusShortname = "spf13"

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = "UA-45616511-1"


[params]
  name = "Giovanni Luca Ciampaglia"
  role = "Research Scientist"
  organization = "Indiana University"
  avatar = "iuni_backyard_2015.png"
  email = "gciampag@iu.edu"
  address = "Network Science Institute, Indiana University, Indiana, 47408, USA."
  phone = "+1 812 855 7261"

  # Date format (refer to Go's date format: http://flippinggodateformat.com )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  date_format = "Mon, Jan 2, 2006"

  # Enable global LaTeX math rendering? If false, you can enable it locally on a per page basis.
  math = false

  # Enable native social sharing buttons?
  sharing = true

  # Link custom CSS and JS assets (relative to /static/css and /static/js respectively)
  custom_css = []
  custom_js  = []

  # Biography section.
  # Section will only be displayed if `content/home/about.md` exists.
  [params.about]
    interests = ["Network Science", "Computational Social Science", "Data Science"]
    str_interests = "Interests"
    str_education = "Education"

    [[params.about.education]]
      course = "PhD in Informatics"
      institution = "University of Lugano"
      year = 2012

    [[params.about.education]]
      course = "MSc in Computer Science"
      institution = "Sapienza University of Rome"
      year = 2007

#     [[params.about.education]]
#       course = "BSc in Artificial Intelligence"
#       institution = "Massachusetts Institute of Technology"
#       year = 2008

  # Selected Publications section.
  # Section will only be displayed if there are publications with `selected = true` in their `+++` preamble.
  [params.publications_selected]
    detailed_list = true
    title = "Selected Publications"
    subtitle = ""

  # Publications section.
  # Section will only be displayed if there are publications in `content/publication/`.
  [params.publications]
    count = 10
    detailed_list = false
    title = "Recent Publications"
    subtitle = ""
    str_all = "More Publications"

  # Posts section.
  # Section will only be displayed if there are posts in `content/post/`.
  [params.posts]
    count = 5
    title = "Recent Posts"
    subtitle = ""
    str_all = "More Posts"
    str_read_more = "Read more"

  # Projects section.
  # Section will only be displayed if there are projects in `content/project/`.
  [params.projects]
    title = "Projects"
    subtitle = "Software, data, and visualizations"

  # Contact section.
  [params.contact]
    enable = true
    title = "Contact"
    subtitle = ""
    autolink = true  # Automatically link email and phone?

  # Social/Academic Networking
  #
  # Icon pack "fa" includes the following social network icons:
  #   twitter, weibo, linkedin, github, facebook, pinterest, google-plus, youtube, instagram, soundcloud
  #   For email icon, use "fa" icon pack, "envelope" icon, and "mailto:your@email.com" as the link.
  #   Full list: https://fortawesome.github.io/Font-Awesome/icons/
  #
  # Icon pack "ai" includes the following academic network icons:
  #   google-scholar, arxiv, orcid, researchgate, mendeley
  #   Full list: https://jpswalsh.github.io/academicons/

  [[params.social]]
    icon = "envelope"
    icon_pack = "fa"
    link = "mailto:gciampag@iu.edu"

  [[params.social]]
    icon = "google-scholar"
    icon_pack = "ai"
    link = "//scholar.google.com/citations?user=ay9uGpcAAAAJ"

  [[params.social]]
    icon = "arxiv"
    icon_pack = "ai"
    link = "//arxiv.org/find/all/1/au:+ciampaglia/0/1/0/all/"

  [[params.social]]
    icon = "github"
    icon_pack = "fa"
    link = "//github.com/glciampaglia"

  [[params.social]]
    icon = "linkedin"
    icon_pack = "fa"
    link = "//www.linkedin.com/in/giovanni-luca-ciampaglia-94101348"

  [[params.social]]
    icon = "calendar"
    icon_pack = "fa"
    link = "//doodle.com/glciampaglia"

#   [[params.social]]
#     icon = "wikipedia-w"
#     icon_pack = "fa"
#     link = "//en.wikipedia.org/wiki/User:Junkie.dolphin"

#   [[params.social]]
#     icon = "orcid"
#     icon_pack = "ai"
#     link = "//orcid.org/0000-0001-5354-9257"


# Navigation Links
#   The weight parameter defines the order that the links will appear in.

[[menu.main]]
  name = "Home"
  url = "#top"
  weight = 1

[[menu.main]]
  name = "Publications"
  url = "#publications"
  weight = 2

[[menu.main]]
  name = "Posts"
  url = "#post"
  weight = 3

[[menu.main]]
  name = "Projects"
  url = "#projects"
  weight = 4

[[menu.main]]
  name = "Teaching"
  url = "#teaching"
  weight = 5

[[menu.main]]
  name = "Contact"
  url = "#contact"
  weight = 6
